# Generated by Django 3.2 on 2021-04-08 23:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('messages', models.TextField(max_length=255)),
                ('commentedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Comments',
                'ordering': ['commentedBy'],
            },
        ),
        migrations.CreateModel(
            name='kamil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jukiNumber', models.IntegerField()),
                ('jukiType', models.TextField(default='TEXT CORANIQUE', max_length=50)),
            ],
            options={
                'db_table': 'juz',
                'ordering': ['jukiNumber'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deviceId', models.TextField(max_length=255)),
                ('fullname', models.TextField(max_length=150)),
                ('zone', models.TextField(max_length=150)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Recital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legend', models.TextField(max_length=255)),
                ('NumberOfKamil', models.PositiveIntegerField()),
                ('NumberOfKamilEnd', models.PositiveIntegerField(default=0)),
                ('recitalStatus', models.TextField(choices=[('ENCOURS', 'ENCOURS'), ('SUSPENDU', 'SUSPENDU'), ('TERMINER', 'TERMINER')], default='ENCOURS', max_length=90)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('dateOfEnd', models.DateTimeField()),
                ('updateddAt', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Recitals',
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('likedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('theComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comment')),
            ],
            options={
                'db_table': 'Likes',
                'ordering': ['theComment', 'likedBy'],
            },
        ),
        migrations.CreateModel(
            name='Juki',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jukiNumber', models.IntegerField()),
                ('ReadingState', models.TextField(choices=[('ENCOURS', 'ENCOURS'), ('TERMINER', 'TERMINER')], default='ENCOURS', max_length=50)),
                ('chosedAT', models.DateTimeField(auto_now=True)),
                ('updateddAt', models.DateTimeField(auto_now=True)),
                ('chosedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('fromRecital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recital')),
            ],
            options={
                'db_table': 'JukiTaked',
                'ordering': ['fromRecital', 'chosedBy'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='commentedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
