# Generated by Django 3.2 on 2021-04-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210409_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juki',
            name='jukiNumber',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
