# Generated by Django 3.2 on 2021-04-09 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_juki_jukinumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juki',
            name='chosedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AlterField(
            model_name='juki',
            name='fromRecital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.recital'),
        ),
    ]
